#!/bin/bash
# Start/stop the MongoDB daemon.
#
### BEGIN INIT INFO
# Provides:          mongodb
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs
# Should-Start:      $named slapd autofs ypbind nscd nslcd
# Should-Stop:       $named slapd autofs ypbind nscd nslcd
# Default-Start:     2 3 4 5
# Default-Stop:          0 1 6
# Short-Description: Start mongodb daemon
# Description:       Start mongodb daemon
#
### END INIT INFO
 
test `whoami` != "root" && echo "You must be root, exiting..." && exit 1
 
homepath="/var/lib/mongo"
daemonpath="$homepath/x86_64-2.4.9/bin"
configpath="$homepath/conf"
 
test ! -x $daemonpath/mongod || test ! -f $configpath/mongodb.conf && echo "Check daemon or conf in $homepath, exiting..." && exit 1
 
function start {
  su - mongodb -c "$daemonpath/mongod --config $configpath/mongodb.conf"
}
 
function stop {
  su - mongodb -c "$daemonpath/mongod --config $configpath/mongodb.conf --shutdown"
}
 
### Main
case "$1" in
  start|stop)
    $1;;
  restart)
    stop
    sleep 3
    start;;
  *)
    echo "Usage: `basename $0` {start|stop|restart}" >&2
    exit 1;;
esac
exit 0